// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALcUQiRWqOhWFDzJeEdUu9b09HGxIdcsc',
    appId: '1:971456015430:web:c81f6c0238360cf4466e47',
    messagingSenderId: '971456015430',
    projectId: 'bootcampmaterial-d3eec',
    authDomain: 'bootcampmaterial-d3eec.firebaseapp.com',
    storageBucket: 'bootcampmaterial-d3eec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCptUegmvvMo0RQxrCOwQ_xkm-1bjb0ZGo',
    appId: '1:971456015430:android:2d83b04f3b1e3edf466e47',
    messagingSenderId: '971456015430',
    projectId: 'bootcampmaterial-d3eec',
    storageBucket: 'bootcampmaterial-d3eec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBXM2L3gm57ngl3bmpWK9C2J6X8JUHgc8',
    appId: '1:971456015430:ios:b95c61d89a749787466e47',
    messagingSenderId: '971456015430',
    projectId: 'bootcampmaterial-d3eec',
    storageBucket: 'bootcampmaterial-d3eec.appspot.com',
    iosClientId: '971456015430-dhvuls94sjtl401cq48aju6c3di3s5pv.apps.googleusercontent.com',
    iosBundleId: 'com.example.reqApiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBXM2L3gm57ngl3bmpWK9C2J6X8JUHgc8',
    appId: '1:971456015430:ios:b95c61d89a749787466e47',
    messagingSenderId: '971456015430',
    projectId: 'bootcampmaterial-d3eec',
    storageBucket: 'bootcampmaterial-d3eec.appspot.com',
    iosClientId: '971456015430-dhvuls94sjtl401cq48aju6c3di3s5pv.apps.googleusercontent.com',
    iosBundleId: 'com.example.reqApiApp',
  );
}
